name: deploy

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@3.5.1
        with:
          node-version: 18.x
      - name: Checkout branch release
        uses: actions/checkout@v3
      - name: Build
        run: npm ci && npm run build
      - name: Keep dist only
        run: mkdir ../_tmp && mv ./* ../_tmp && mv ../_tmp/dist/* . && rm -R ../_tmp
      - name: Publish as page
        uses: Automattic/action-commit-to-branch@master
        with: 
          branch: page-dist
          commit_message: "[Action: Deploy] Update pages."
          
